image:
  tag: ${COMMIT_SHA}

api:
  domain: ${K8S_NAMESPACE}.${DOMAIN_SUFFIX}

db: 
  auth:
    clientId: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}

tls: true

namespace: ${K8S_NAMESPACE}

db_mode: persistent

mariadb:
  enabled: true
  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: DoesNotExist
