---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: {{ .Values.namespace }}
data:
  config.json: |-
      {
          "backend": {
              "api": {
              },
              "auth": {
                  "clientId": "{{ .Values.auth.clientId }}",
                  "clientSecret": "{{ .Values.auth.secret }}",
              }
          }
      }
