/**
 * Copyright (c) 2015-present, CWB SAS
 *
 * This source code is licensed under the GPL v2.0+ license found in the
 * LICENSE file in the root directory of this source tree.
 */
export const API_GETBOTS = "API_GETBOTS";
export const API_CREATEBOT = "API_CREATEBOT";
export const API_SAVEBOT = "API_SAVEBOT";
export const API_IMPORT = "API_IMPORT";
export const API_PUBLISH = "API_PUBLISH";
export const API_SELECT_BOT = "API_SELECT_BOT";
export const API_BOT_GET_VARIABLES = "API_BOT_GET_VARIABLES";
export const API_BOT_SET_VARIABLES = "API_BOT_SET_VARIABLES";
export const API_BOT_GET_LOCAL_VARIABLES = "API_BOT_GET_LOCAL_VARIABLES";
export const API_BOT_SET_LOCAL_VARIABLES = "API_BOT_SET_LOCAL_VARIABLES";
export const API_BOT_GET_ENTITIES = "API_BOT_GET_ENTITIES";
export const API_BOT_SET_ENTITIES = "API_BOT_SET_ENTITIES";

export const API_GETINTENTS = "API_GETINTENTS";
export const API_SENDINTENT = "API_SENDINTENT";
export const API_DELETEINTENT = "API_DELETEINTENT";
export const API_MOVEINTENT = "API_MOVEINTENT";

export const API_BOTS_PARAMETERS = "API_BOTS_PARAMETERS";

// API middlewares constants
export const API_GETMIDDLEWARES = "API_GETMIDDLEWARES";
export const API_SETMIDDLEWARE = "API_SETMIDDLEWARE";
export const API_DELETEMIDDLEWARE = "API_DELETEMIDDLEWARE";

// API webhooks constants
// export const API_GETWEBHOOKS = "API_GETWEBHOOKS";
// export const API_SETWEBHOOK = "API_SETWEBHOOK";
// export const API_DELETEWEBHOOK = "API_DELETEWEBHOOK";

// API sandbox constants
export const API_SB_GETMESSAGES = "API_SB_GETMESSAGES";
export const API_SB_UPDATEMESSAGES = "API_SB_UPDATEMESSAGES";
export const API_SB_SENDMESSAGE = "API_SB_SENDMESSAGE";
export const API_SB_GETCONTEXT = "API_SB_GETCONTEXT";
export const API_SB_RESET = "API_SB_RESET";
export const APP_SET_SB_CONVERSATION = "APP_SET_SB_CONVERSATION";
// App logic constants
export const APP_UPDATEPUBLISHER = "APP_UPDATEPUBLISHER";
export const APP_SELECTINTENT = "APP_SELECTINTENT";
export const APP_SELECTIO = "APP_SELECTIO";
export const APP_UNSELECTIO = "APP_UNSELECTIO";
export const APP_UPDATEINTENT = "APP_UPDATEINTENT";
export const APP_SETINTENTACTION = "APP_SETINTENTACTION";
export const APP_DELETEINTENTACTION = "APP_DELETEINTENTACTION";
export const APP_SETNEWACTIONS = "APP_SETNEWACTIONS";
export const APP_DELETENEWACTIONS = "APP_DELETENEWACTIONS";
export const APP_SELECTENTITY = "APP_SELECTENTITY";
export const APP_SELECTVARIABLE = "APP_SELECTVARIABLE";
export const APP_SELECTFUNCTION = "APP_SELECTFUNCTION";
// API metrics
export const API_GETMETRICS = "API_GETMETRICS";

// API admin
export const API_GETTEMPLATES = "API_GETTEMPLATES";
export const API_GETLANGUAGES = "API_GETLANGUAGES";
export const API_GET_VARIABLES = "API_GET_VARIABLES";
export const API_SET_VARIABLES = "API_SET_VARIABLES";
export const API_GET_ENTITIES = "API_GET_ENTITIES";
