---
project: ci

tasks:
  _circle_notify:
    cmd: circle_notify.sh

  _app_version:
    cmd: |-
      echo "export APP_VERSION=`jq -r .version package.json`"

  ci_build:
    cmd: |-
      eval $(myke -v=0 _app_version)
      $myke build --TAG={{.COMMIT_SHA | required}} --COMMIT_SHA={{.COMMIT_SHA}} --BUILD_NUMBER={{.BUILD_NUMBER}}
      $myke _push --TAG={{.COMMIT_SHA}}
      helm init --client-only \
        && $myke _publish_charts \
        --CHART_VERSION={{.CHART_VERSION_SEM | required}}-{{.COMMIT_SHA}}

  ci_promote:
    cmd: |-
      eval $(myke -v=0 _app_version)
      $myke _promote --TAG={{.COMMIT_SHA | required}}
      helm init --client-only \
        && $myke _publish_charts \
        --CHART_VERSION={{.CHART_VERSION_SEM | required}}

  deploy:
    cmd: |-
      $myke _prepare || true
      helm dependency update {{.CHART_DIR}}
      (envsubst <{{.CHART_DIR}}/values.yaml; envsubst <{{.CHART_DIR}}/values.{{.K8S_ENV}}.yaml) \
      | helm upgrade --install --wait --debug \
      --namespace {{ .K8S_NAMESPACE }} \
      {{ .K8S_NAMESPACE }}-{{ .APPLICATION_SHORT_NAME }} ./{{.CHART_DIR}} \
      {{ .HELM_XTRA_ARGS }} -f -

  preview:
    cmd: |-
      $myke _prepare || true
      helm dependency update {{.CHART_DIR}}
      (envsubst <{{.CHART_DIR}}/values.yaml; envsubst <{{.CHART_DIR}}/values.{{.K8S_ENV}}.yaml) \
      | helm template ./{{.CHART_DIR}} -f -
      
  dry_run:
    cmd: |-
      $myke _prepare || true
      helm dependency update {{.CHART_DIR}}
      (envsubst <{{.CHART_DIR}}/values.yaml; envsubst <{{.CHART_DIR}}/values.{{.K8S_ENV}}.yaml) \
      | helm upgrade --install --wait --dry-run --debug \
      --namespace {{ .K8S_NAMESPACE }} \
      {{ .K8S_NAMESPACE }}-{{ .APPLICATION_SHORT_NAME }} ./{{.CHART_DIR}} \
      {{ .HELM_XTRA_ARGS }} -f -
